[package]
name = "alley"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1", features = [ "dialog-open", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
lazy_static = "1"
salvo = { version = "0.63", features = ["serve-static", "websocket"] }
tokio = { version = "1", features = ["macros"] }
tokio-util = "0.7"
tracing = "0.1"
tracing-subscriber = "0.3"
local-ip-address = "0.5"
qrcode-generator = "4"
bytes = '1'
futures = "0.3"
read-progress-stream = "1"
log = "0.4"
simplelog = { version = "0.12", features = ["paris"] }
time = { version = "0.3", features = ['formatting'] }
thiserror = "1"


[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
