name: "publish"
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-22.04]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install missing Rust target for universal Mac build
        if: matrix.platform == 'macos-latest'
        run: rustup target add aarch64-apple-darwin

      - name: Get version with alpha or beta deleted on Windows
        if: matrix.platform == 'windows-latest'
        run: |
          cd src-tauri
          $version = node before-build.js
          echo "BUILD_VERSION=$version" >> $Env:GITHUB_ENV

      - name: Get version
        if: matrix.platform != 'windows-latest'
        run: |
          cd src-tauri
          version=$(node before-build.js)
          echo "BUILD_VERSION=$version" >> $GITHUB_ENV

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: pnpm install:all

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: ${{ format('v{0}', env.BUILD_VERSION == '' && '__VERSION__' || env.BUILD_VERSION) }}
          releaseName: ${{ format('v{0}', env.BUILD_VERSION == '' && '__VERSION__' || env.BUILD_VERSION) }}
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{matrix.platform == 'macos-latest' && '-t aarch64-apple-darwin' || matrix.platform == 'windows-latest' && '-t x86_64-pc-windows-msvc' || '-t x86_64-unknown-linux-gnu'}}
