name: "publish"
on:
  push:
    branches:
      - release

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}
      package_version: ${{ env.PACKAGE_VERSION }}

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: get version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: create release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${process.env.PACKAGE_VERSION}`,
              name: `v${process.env.PACKAGE_VERSION}`,
              body: 'Take a look at the assets to download and install this app.',
              draft: true,
              prerelease: process.env.PACKAGE_VERSION.indexOf('alpha') >= 0,
            })
            return data.id

  build-tauri:
    needs: create-release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        # platform: [macos-latest, ubuntu-22.04, windows-latest]
        platform: [ubuntu-22.04]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: install pnpm
        with:
          version: 8
          run_install: false

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install missing Rust target for universal Mac build
        if: matrix.platform == 'macos-latest'
        run: rustup target add aarch64-apple-darwin

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: get version with alpha or beta deleted on Windows
        if: matrix.platform == 'windows-latest'
        run: |
          cd src-tauri
          $version = node before-build.js
          echo "BUILD_VERSION=$version" >> $Env:GITHUB_ENV

      - name: install frontend dependencies
        run: pnpm install:all

      - uses: tauri-apps/tauri-action@v0
        if: matrix.platform == 'macos-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          args: "-t aarch64-apple-darwin"

      - uses: thep0y/tauri-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          RENAME_RULE: '{"searchValue": "${{ env.BUILD_VERSION }}", "replaceValue": "${{ needs.create-release.outputs.package_version }}"}'
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          rename: ${{ matrix.platform == 'windows-latest' && env.RENAME_RULE || '' }}

  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    needs: [create-release, build-tauri]

    steps:
      - name: publish release
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
          PACKAGE_VERSION: ${{ needs.create-release.outputs.package_version }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: true,
              prerelease: process.env.PACKAGE_VERSION.indexOf('alpha') >= 0,
            })

  upload_mirror_json:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    needs: [create-release, publish-release]
    env:
      release_id: ${{ needs.create-release.outputs.release_id }}

    steps:
      - uses: actions/checkout@v4

      - name: get latest.json
        id: get-latest
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const assets = await github.rest.repos.listReleaseAssets({
              owner: owner,
              repo: repo,
              release_id: process.env.release_id,
              per_page: 50,
            });
            const asset = assets.data.find((e) => e.name === 'latest.json');

            if (!asset) throw new Error("latest.json was not found in release assets");

            const data = await github.request(
              "GET /repos/{owner}/{repo}/releases/assets/{asset_id}",
              {
                owner: owner,
                repo: repo,
                asset_id: asset.id,
                headers: {
                  accept: "application/octet-stream",
                },
              },
            );

            return Buffer.from(data.data).toString()

      - name: new mirror latest.json
        env:
          TEXT: ${{ steps.get-latest.outputs.result }}
        run: |
          cd src-tauri
          node mirror-latest-json.js

      - uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: thepoy
          server: thepoy.cc
          password: ${{ secrets.TAURI_KEY_PASSWORD }}
          local_path: ./src-tauri/latest.json
          remote_path: /home/thepoy/app/alley
          sftpArgs: "-o ConnectTimeout=5"
